### ISSUE TITLE
족보 판정 코드의 추가적인 테스트가 필요합니다.

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#14]
jokboTest2.py 파일의 점수제 메커니즘이 완전히 구현되었는지에 대한 추가적인 검증이 필요합니다.

<img width="937" alt="IndexError" src="https://user-images.githubusercontent.com/96714275/176936486-aa74ff3a-981d-41f5-bd70-b2a3254f3741.PNG">

예상되는 오류로는 위와 같은 인덱스 오류가 있는데
만약 해당 오류 발견시 오류 메시지 위에 디버깅용으로 출력되는 스코어(정수)를 제보해주시기 바랍니다.

**Comment by hcm1206** [comment]
현재 A 투페어 상황에서 인덱스 오류 발생 확인.
수정된 버전의 코드가 7/2일 내로 업데이트 될 예정입니다.

**Comment by hcm1206** [comment]
A 스트레이트 점수 판정 문제 확인(스트레이트 중에서 최저 점수로 출력).
아마 같은 로직을 쓰는 스트레이트 플러시 판정에서도 동일한 문제가 발생할 것으로 추정됩니다.

**Comment by hcm1206** [comment]
22/07/22 업데이트
A 투페어 인덱스 오류가 수정되었습니다.
스트레이트 로직을 새로 구현하여 A 스트레이트 점수 판정을 수정하였습니다.

스트레이트 플러시는 아직 확인 중입니다.

**Comment by hcm1206** [comment]
22/07/04 업데이트
이제 스트레이트 플러시에서도 A 스트레이트(로열)을 정상적으로 판정하도록 수정하였습니다.

현재 족보 판정 알고리즘을 본 게임에 적용시켰으나 아직 추가적인 테스트를 진행 중입니다.
판정에 문제가 있거나 로직 오류 발견시 제보해주시기 바랍니다.

**Comment by hcm1206** [comment]
<img width="326" alt="bug" src="https://user-images.githubusercontent.com/96714275/177185956-6cacf637-222c-4155-a9fb-28eed637c880.PNG">
이건 또 무슨 로직 오류일까요
돌겠네

**Comment by hcm1206** [comment]
<img width="525" alt="bug2" src="https://user-images.githubusercontent.com/96714275/177189214-cc2a6b15-f99d-4a16-8348-ed072b967d4b.PNG">

A 투페어인데 J 투페어로 판정하는 오류 발견

**Comment by hcm1206** [comment]
<img width="329" alt="flushbug" src="https://user-images.githubusercontent.com/96714275/177237961-9c49b136-838b-4be2-80e8-fd53afb51e47.PNG">
플러시 족보 판정 오류 확인

**Comment by hcm1206** [comment]
A 플러시를 판정하지 못하는 로직 오류를 발견하여 조치 완료하였습니다.
다음 업데이트에 수정된 코드 배포 예정

**Comment by hcm1206** [comment]
<img width="336" alt="찐스트레이트플러시" src="https://user-images.githubusercontent.com/96714275/177283109-9885583e-979b-4200-8066-4509ca89fa04.PNG">

스트레이트 플러시에서도 숫자 판정 오류가 발견되었습니다

**Comment by mnyu123** [comment]
> <img alt="bug2" width="525" src="https://user-images.githubusercontent.com/96714275/177189214-cc2a6b15-f99d-4a16-8348-ed072b967d4b.PNG">
> 
> A 투페어인데 J 투페어로 판정하는 오류 발견

> 투페어 판정 족보에 에이스 투페어는 특별한 경우로 취급해 점수를 다르게 반영해 판정하게 함.

**Comment by mnyu123** [comment]
> <img alt="flushbug" width="329" src="https://user-images.githubusercontent.com/96714275/177237961-9c49b136-838b-4be2-80e8-fd53afb51e47.PNG">
> 
> 플러시 족보 판정 오류 확인

> 투페어 문제 해결 후 오류 수정완료

**Comment by hcm1206** [comment]
<img width="320" alt="bug4" src="https://user-images.githubusercontent.com/96714275/177713903-bcf9156d-cadb-44d6-b718-3a60bd08791f.PNG">

스트레이트 플러시 오류 발견

**Comment by hcm1206** [comment]
> <img alt="bug4" width="320" src="https://user-images.githubusercontent.com/96714275/177713903-bcf9156d-cadb-44d6-b718-3a60bd08791f.PNG">
> 
> 스트레이트 플러시 오류 발견
<img width="324" alt="bug4_1" src="https://user-images.githubusercontent.com/96714275/177726414-b4191763-d9a2-4026-9086-b30584c10680.PNG">
A 스트레이트 상황에서 계속 스트레이트 플러시 판정이 나는 것으로 보아 로얄 스트레이트 플러시 판정에 문제가 있는 것으로 보입니다.

**Comment by hcm1206** [comment]
<img width="326" alt="superBug" src="https://user-images.githubusercontent.com/96714275/178103000-0b08c924-5b5f-4dba-abcc-b53ede6ec285.PNG">

트리플 2개가 중복으로 출현시 포카드로 판정하는 버그 발견

**Comment by hcm1206** [comment]
<img width="326" alt="twoPairACEbug" src="https://user-images.githubusercontent.com/96714275/178103013-b8f62272-1e57-4b1a-82d3-4bfa8c288fac.PNG">
에이스 투페어가 제대로 판정되지 않는 버그가 재발하고 있습니다.
수정한 알고리즘이 제대로 동작되고 있지 않거나 수정된 버전이 마스터 브랜치에 적용되지 않은 듯 합니다.

**Comment by hcm1206** [comment]
현재 족보 알고리즘 개편 작업중.
추가 테스트 필요

**Comment by hcm1206** [comment]
새로운 카드 인덱스 체계 개편으로 인하여 재검증 필요
