### ISSUE TITLE
족보 판정에 키커 판정 추가 필요 / 220705

### ISSUE THREAD

**Issue by mnyu123** [hcm1206/PokerGame#20]
키커 판정상황 (키커싸움==일명 족보싸움 / 그리고 페어 상황 + 트리플 + 포카드 상황)에서 추가적인 한번의 족보싸움 없이 무조건 동점으로 판단하는 문제 발견

**Comment by hcm1206** [comment]
참조

<img width="371" alt="reference" src="https://user-images.githubusercontent.com/96714275/177666247-383326c4-c405-4cd4-8690-a3f08fad174e.PNG">

Cards.py 파일의 코드 중 일부입니다.
getMyDeckCards(), getCpuDeckCards() 메소드가 정의되어있는데
해당 메소드는 현재 플레이어 및 CPU의 개인 카드 2장의 정보를 리스트로 (ex. [25,42]와 같이) 출력하는 메소드입니다.
해당 메소드를 사용하여 리턴받은 리스트의 카드 숫자를 비교하면 키커를 구현할 수 있을 것으로 보입니다.

**Comment by mnyu123** [comment]
알겠습니다.

**Comment by hcm1206** [comment]
키커 추가 완료

**키커 판정 승리 시**
<img width="334" alt="win" src="https://user-images.githubusercontent.com/96714275/178102772-6b9a0b5f-c4b9-42b9-b371-1871dd3fa56a.PNG">

**에이스도 정상적으로 판정 확인**
<img width="333" alt="win(ACE)" src="https://user-images.githubusercontent.com/96714275/178102835-4310fcc4-b3a9-481b-966f-7f4bbfcdfa19.PNG">

**키커 판정 패배 시**
<img width="334" alt="lose" src="https://user-images.githubusercontent.com/96714275/178102858-5586cff3-722d-499d-a224-e82a6f83f714.PNG">

키커 판정이 올바르게 이루어지는지 지속적인 테스트 바랍니다.
