### ISSUE TITLE
카드 번호 인덱스 개편

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#30]
[A,2,3,4,5,6,7,8,9,10,J,Q,K] 순으로 지정되어있던 기존 카드 번호 인덱스를
[2,3,4,5,6,7,8,9,10,J,Q,K,A] 순으로 개편하였습니다.

이에 따라 족보 판정 등에서 변경된 인덱스가 제대로 호환되는지 검증이 필요합니다.

**Comment by mnyu123** [comment]
22-07-12 기준 모두 호환 되는것으로 확인 되었습니다.

**Comment by hcm1206** [comment]
추가적인 오류가 발견된다면 코맨트해주시기 바랍니다.

**Comment by hcm1206** [comment]
<img width="325" alt="AstraightError" src="https://user-images.githubusercontent.com/96714275/179353230-307e4af0-6fba-464f-9a33-d2522e708a41.PNG">

A,2,3,4,5,6 (6 스트레이트)를 A 스트레이트로 판정하는 오류 확인

**Comment by hcm1206** [comment]
<img width="326" alt="qlfdjajrdmf" src="https://user-images.githubusercontent.com/96714275/179359938-c220cd6c-42e8-49cc-9691-f57bc9a056e9.PNG">
시즌 5호 스트레이트 플러시 버그 발생

**Comment by mnyu123** [comment]
시즌 5호 버그는 A스트레이트 이슈에 같이 버그가 일어난 이유를 적었습니다.

**Comment by hcm1206** [comment]
22-07-23 레거시 인덱스 체계로 롤백
