### ISSUE TITLE
앞으로의 계획(로드맵) 및 추가 작업 건의

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#32]
현재 기본적인 게임 룰은 거의 구현되었다고 생각이 됩니다.

현재 진행 예정인 단기적인 작업으로는

- 추가적인 족보 판정 검증
- UI 구조 개편(Tkinter config 함수 적용)
- window 파일 분할
- 기타 최적화

와 같이 버그 수정이나 최적화, 코드 가독성 향상 등 자잘한 코드 정리가 진행될 것으로 보입니다.

******

코드 정리가 끝나고 안정화되면 다음과 같은 장기적인 플랜도 구상 중입니다.
- CPU 인공지능 향상 : 딥러닝을 적용해 실제 사람과 같이 게임을 플레이하는 AI 구현
- 멀티 플레이 : 서버단을 구축하여 실제 다른 플레이어와 포커 게임을 할 수 있도록 구현

두가지 모두 딥러닝 기술이나 백엔드 기술이 뒷받침되어야 하는 큰 작업이 될 것이므로 개발 일정을 넉넉하게 잡으려 합니다.

******

기능 추가 또는 개편되었으면 하는 점이 있을 경우 언제든지 건의해주시기 바랍니다.

**Comment by mnyu123** [comment]
cpu 게임능력은 장기적이지만 단기적으로 쉬운 개발부터 시작해서 딥러닝 까지 적용하는것을 생각하고 있습니다
(예를 들어, 지금은 내가 배팅한 금액만큼 배팅이지만 , 특정 조건에만 따라서 폴드나 올인을 선택하는 것부터 시작해 딥러닝으로)

**Comment by mnyu123** [comment]
조커모드를 따로 추가해 그것을 실행하려면 하나의 버튼으로 "게임모드"를 변경하는 것도 아이디어가 있습니다.

**Comment by mnyu123** [comment]
그리고 게임 턴을 누적해서 블라인드가 점점 올라가게 하는 룰 추가 건의

**Comment by mnyu123** [comment]
추가적으로 제가 직접 만들예정인 플레이어에게 족보가 띄워질때마다 이길 확률을 따로 보여주는 것을 구상중 입니다.
(버튼 등으로 켰다 껐다 할 생각중 - 버튼 이름은 Guide로 예정)

**Comment by hcm1206** [comment]
> 그리고 게임 턴을 누적해서 블라인드가 점점 올라가게 하는 룰 추가 건의

일단 블라인드의 경우 '게임 초기화' 버튼과 같은 메뉴 바 형식을 통해 임의로 설정할 수 있게 할 계획입니다

**Comment by hcm1206** [comment]
> > 그리고 게임 턴을 누적해서 블라인드가 점점 올라가게 하는 룰 추가 건의
> 
> 일단 블라인드의 경우 '게임 초기화' 버튼과 같은 메뉴 바 형식을 통해 임의로 설정할 수 있게 할 계획입니다

블라인드 설정 기능 추가 완료.
다만 설정 가능한 블라인드의 범위를 어떻게 지정할지 의논이 필요할 것 같습니다.
일단은 임의로 100~5000 사이의 범위로 블라인드를 지정할 수 있도록 설정했습니다.

**Comment by hcm1206** [comment]
> 추가적으로 제가 직접 만들예정인 플레이어에게 족보가 띄워질때마다 이길 확률을 따로 보여주는 것을 구상중 입니다. (버튼 등으로 켰다 껐다 할 생각중 - 버튼 이름은 Guide로 예정)

해당 기능의 경우 본 게임에 바로 적용하기보다는 
JokboTest 파일처럼 테스트 파일에서 실험해본 후 
해당 매커니즘을 클래스화하여 본게임에 적용하는 것이 좋을 것 같습니다.

예를 들어 패의 카드 2장을 이용하여 승리 확률을 계산해주는 로직을 구현해본 후 
해당 로직이 원활하게 작동하는지 테스트 파일 상에서 UI로 실험해본다던가 여러 방법이 있을 겁니다.

일단 해당 확률 계산 로직을 구현하여 더미 파일로 올려주시면 적절한 UI를 구현해드리겠습니다.

**Comment by hcm1206** [comment]
22-07-25 업데이트

현재 상대 AI를 구현하기 위한 설계 및 밑작업을 실시하고 있습니다.
지금 구현되어있는 매커니즘으로는 무조건 플레이어에 행동에 의해서만 게임이 진행되는 구조이기 떄문에
앞으로는 플레이어의 배팅이 끝난 후 AI가 자신의 패를 보고 판단하여 폴드나 추가 배팅을 진행할 지의 여부를 결정하도록 구조를 변경해야 할 필요가 있어 이에 대한 작업을 진행하는 중입니다.

******

AI 같은 경우에는 일단 현재 패의 점수만을 토대로 행동을 결정하는 단순한 형태로 구현할 계획이며 차차 AI 향상을 위한 기타 알고리즘이나 딥러닝 기술 적용 등을 검토할 계획입니다.
여러 번 언급하였듯이 AI 구현은 장기적인 관점에서 바라보고 구현할 계획이라 상당한 개발 시간이 소요될 예정입니다.
