### ISSUE TITLE
키커 판정 문제

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#34]
<img width="329" alt="질문" src="https://user-images.githubusercontent.com/96714275/179353398-089c944d-9fb9-47ff-bdeb-a483e663a2ac.PNG">

테스트 중 키커 판정에 대하여 의문이 생겨 질문합니다.

상기 예시의 경우 각자의 개인 패 모두 A가 하나씩 존재하고 커뮤니티 패에 A가 존재하여
서로 A 원페어 판정으로 동일 족보인 상황입니다. 

따라서 키커판정을 해야 하는데 
이런 경우에는 **이미 족보 계산에 사용된 A가 아니라 'K'와 '5'를 키커 계산에 사용해야 하는 것 아닌지요?**

현재 키커 판정은 단순히 개인 패 카드 2장 중 가장 높은 카드끼리 비교하는 방식이기 때문에
족보 판정에 개인 카드가 사용되었을 때 해당 카드를 키커 판정에서 제외하는 기능이 존재하지 않습니다.

**Comment by mnyu123** [comment]
네 K하고 5를 비교해야하는게 판정에 맞지만 그 기능은 없는걸로 압니다

**Comment by hcm1206** [comment]
> 네 K하고 5를 비교해야하는게 판정에 맞지만 그 기능은 없는걸로 압니다

그럼 해당 기능 구현해오시오

**Comment by hcm1206** [comment]
대강 코드 분석해봤는데 이거 고치려면 골치가 많이 아프겠습니다

짐작되는 해결 방법으로는 카드 인덱스를 따로 저장해 놓고 
특정 인덱스의 카드가 족보 판정에 사용되었을 시 
그 인덱스의 카드를 키커 판정에 사용하지 않도록 하는 등의 방식이 있겠네요

그런데 이런 식으로 만드려면 족보 판정할 때 매번 인덱스 확인을 하는 과정을 집어넣는 등의 귀찮은 과정이 필요할 것 같고
차칫하면 또 새로운 키커 오류를 일으킬 우려가 있어서 건드리기 만만치 않아보입니다

일단은 더 괜찮은 알고리즘으로 구현할 수 있을지 연구해보도록 하죠

**Comment by mnyu123** [comment]
> 대강 코드 분석해봤는데 이거 고치려면 골치가 많이 아프겠습니다
> 
> 짐작되는 해결 방법으로는 카드 인덱스를 따로 저장해 놓고 특정 인덱스의 카드가 족보 판정에 사용되었을 시 그 인덱스의 카드를 키커 판정에 사용하지 않도록 하는 등의 방식이 있겠네요
> 
> 그런데 이런 식으로 만드려면 족보 판정할 때 매번 인덱스 확인을 하는 과정을 집어넣는 등의 귀찮은 과정이 필요할 것 같고 차칫하면 또 새로운 키커 오류를 일으킬 우려가 있어서 건드리기 만만치 않아보입니다
> 
> 일단은 더 괜찮은 알고리즘으로 구현할 수 있을지 연구해보도록 하죠

>페어같은 족보들이 True일때 라는 조건을 둬서 True면 내 핸드(2장)의 인덱스를 바꾸는것(바꾼다고 말은 했지만 위의 예시로는 키커를 'A'로 보고있으니까 원페어==True 에서 키커 판정용으로 가져가는 인덱스를 다른 카드로 바꾸는것)은 어떨까요?

**Comment by hcm1206** [comment]
일단 떠오른게 하나 있는데 위의 예시를 예로 들자면 
'A' 원페어 상황에서 원페어에 사용된 'A'를 키커로 사용하면 안된다는 점에 주목해봅시다.
'A' 원페어이므로 'A'가 키커가 아닌 각각 'K'와 '5'가 키커로 사용되어야 한다.
라는 규칙을 이용하여 수도 코드로 만들어보면
******
number == A, jokbo == '원페어',kicker == A 일때

if number == kicker
    kicker = (패의 다른 카드 숫자 : ex. K or 5)
******
이런 식으로 코드를 사용하면 되지 않을까 싶습니다.
다만 이러한 알고리즘이 모든 족보판정에 통용되는 논리구조인지 검증이 필요합니다.

**Comment by hcm1206** [comment]
<img width="327" alt="solvedguess" src="https://user-images.githubusercontent.com/96714275/183086567-91fe8500-d44f-4476-914b-685c56367aa3.PNG">

일단 상기 알고리즘대로 코드를 수정해본 결과 의도대로 작동은 하는 것으로 보입니다.
다만 다양한 키커 상황에서 제대로 작동하는지 검증은 계속 진행해야 할 것으로 보입니다.

**Comment by hcm1206** [comment]
<img width="328" alt="foldsolved" src="https://user-images.githubusercontent.com/96714275/183254882-2c77acde-0cfb-41c1-9875-9ef295050887.PNG">

저번 업데이트에서 폴드 시 키커 판정 로직도 수정했어야 하는데 누락되었습니다.
22년 8월 7일 내에 수정된 파일 배포 예정입니다.

**Comment by hcm1206** [comment]
일단은 별 문제가 없는 것으로 판단됩니다.
혹여나 문제 발견시 새로운 이슈를 파서 제보해주세요.
