### ISSUE TITLE
A스트레이트 문제

### ISSUE THREAD

**Issue by mnyu123** [hcm1206/PokerGame#36]
각각의 미묘하게 다른 족보가 이야기가 달라 판정이 이상하게 된 문제가 있습니다.
A스트레이트는 스트레이트 중 가장 낮은 족보이므로 수정이 필요합니다

**Comment by mnyu123** [comment]
> 각각의 미묘하게 다른 족보가 이야기가 달라 판정이 이상하게 된 문제가 있습니다. A스트레이트는 스트레이트 중 가장 낮은 족보이므로 수정이 필요합니다

> 스트레이트 , 스트레이트 플러쉬 문제는 스트레이트 플러쉬 족보에서 set [ 8 , 9 , 10 , 11 , 12 ] 로 되어있는 조합이 들어온다면 무조건 스트레이트 플러쉬로 보는 문제였습니다(문양 보지도 않고 숫자만 저렇게 나온다면) 
> 숫자를 확인하고 조건을 걸어 문양까지 맞아야 스트레이트플러시로 보는 조건을 걸어야 하며 , 

> 10 , J , Q , K , A 족보에서의 판정은 K스트레이트 score = 511 점으로 변경되게 할것입니다. ( 스트레이트에서 A가 가장 작은 족보여야 함으로 )

**Comment by hcm1206** [comment]
22-07-23 업데이트
이전 버전 카드 인덱스 체계로 롤백하여 해당 오류가 수정되었습니다.
