### ISSUE TITLE
카드 인덱스 체계 롤백

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#40]
2022년 7월 12일에 카드 인덱스 번호 개편 작업을 실시한 후 최근까지 테스트를 진행하였으나
수정되었던 버그가 재발하는등 기존 인덱스 번호 체계에 비해 불안정하다는 판단이 들어
**이전 버전(2022년 7월 9일) 카드 인덱스 체계로 롤백하였습니다.**

롤백을 통해 기존에 발생하던 스트레이트 버그 등은 일차적으로 해결된 것으로 보이고
이전 버전에서 고치지 못했던 포카드 버그와 에이스 판정 버그 등도 수정하였으며
구 버전 인덱스 체계에 맞게 이후에 추가된 키커 시스템과도 호환되도록 하는 작업을 진행했습니다.

일단 현재까지는 별다른 오류가 확인되지 않은 상태지만 테스트를 통해 추가적인 오류가 있는지 검증바랍니다.

**Comment by mnyu123** [comment]
카드 번호 롤백은 부적절합니다
에이스를 아무리생각해도 0번같은 낮은 인덱스로 주는것보다 높은 12번으로 주는게 더 옳다고 봅니다
테스트후 버그가 있으면 제보하겠습니다

**Comment by hcm1206** [comment]
> 카드 번호 롤백은 부적절합니다 에이스를 아무리생각해도 0번같은 낮은 인덱스로 주는것보다 높은 12번으로 주는게 더 옳다고 봅니다 테스트후 버그가 있으면 제보하겠습니다

이미 점수 계산할 때 A 카드를 가장 높은 점수로 자동 치환하는 기능이 존재하기 때문에 A에 인덱스 번호를 0으로 할당하던 12로 할당하던 결과적으로는 A에 가장 높은 판정을 내리는 기능은 동일하게 작동합니다.
인덱스 번호는 말 그대로 그냥 번호일 뿐 그것이 궁극적으로 인덱스 번호 = 점수를 뜻하는 것이 아니기 때문에 굳이 한 가지를 고집할 필요는 없죠.

그리고 개편된 체계가 안정적으로 작동되면 모르겠으나 계속 테스트 해본 결과 구 체계에서 수정했던 버그들이 끊임없이 재발하고 또다른 새로운 오류가 발생하는 등 구 체계에 비해 안정성 면에서 메리트가 떨어지는 것으로 판단되어 수정한 것입니다.

일단 모든 파일은 브랜치로 백업된 상태이므로 나중에 얼마든지 되돌릴 수 있으니 추이를 지켜보겠습니다.
