### ISSUE TITLE
정상적인 판정인지 확인 바랍니다

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#41]
<img width="329" alt="question" src="https://user-images.githubusercontent.com/96714275/180609674-be224df5-bbe2-4145-a1bc-b78cc40976b9.PNG">

**Q1. 위와 같이 서로 노페어인 상황에서도 키커를 판정합니까?**

<img width="328" alt="question2" src="https://user-images.githubusercontent.com/96714275/180609712-19c66cd8-7be4-4cc0-bf3a-9790ec0920ad.PNG">

**Q2. 위와 같은 투페어 상황에서 상대 키커를 페어인 카드 기준으로 판정하는게 맞습니까?**

설명이 제대로 전달되었는지는 모르겠지만 이미지를 보시고 키커 판정이 정상적으로 진행되었는지를 체크해 주시면 감사하겠습니다.

**Comment by mnyu123** [comment]
Q1. 네
Q2. 네 Q페어니까 보유 카드중에 높은게 8이니까요
