### ISSUE TITLE
넘파이 배열 활용 건의

### ISSUE THREAD

**Issue by hcm1206** [hcm1206/PokerGame#45]
현재 카드 정보 계산을 파이썬의 기본 리스트를 활용하여 진행하고 있는데
이걸 넘파이 배열을 이용하면 어떨까 싶은 생각이 듭니다.

예를 들어 카드 인덱스 리스트에서 카드 숫자만 뽑아오려면 for문을 돌리고 새로운 리스트를 생성하고 등등...
과정이 다소 복잡한데
넘파이 배열을 이용하면 넘파이의 브로드캐스트라던가 뭐 다양한 기능을 통해 코드를 줄이거나 성능을 개선할 수 있을 것 같습니다.

네 물론 코드 뜯어고치려면 또 삽질이 엄청 필요할 것이고 이게 또 생각대로 작동할지는 모르겠습니다
그냥 개인적인 의견입니다

**Comment by mnyu123** [comment]
넘파이를 사용하는것은 좋은 생각입니다
넘파이로 관리하는 리스트 환경에서도 기존의 리스트 환경과 같이
호출/삽입/ 등 연산이 가능한지 찾아봐야할것 같습니다.
개인적인 생각으로는 추측이지만 코드 단순화나 가독성은 엄청 간편하게 바뀔것 같으나 세부적으로 리스트를 건드리는 등의 커스텀은 어려울것 같습니다.. 또 기존리스트 & 넘파이리스트 둘이 혼동해서 수정하는 일도 발생하는경우도 있을것 같습니다

**Comment by hcm1206** [comment]
일단은 보류하겠습니다.
코드 가독성을 높이는 것은 좋으나 그 외에 넘파이 기능을 활용할만한 것이 있을지 미지수이고
데이터 구조를 넘파이 배열로 바꾸려면 코드를 싹 갈아엎어야 하는데 안정성을 확보할 수 있을지도 확실치 않습니다.
